In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    r"C:\Users\HP\Downloads\Amazon Sale Report\Amazon Sale Report.csv",
    low_memory=False
)

df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [3]:
df.shape

(128975, 24)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [6]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [9]:
df.dtypes

index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
Unnamed: 22            object
dtype: object

In [10]:
df['Unnamed: 22'].value_counts(dropna=False)

Unnamed: 22
False    79925
NaN      49050
Name: count, dtype: int64

In [11]:
df['index'].head()

0    0
1    1
2    2
3    3
4    4
Name: index, dtype: int64

In [12]:
df['Date'].head()

0    04-30-22
1    04-30-22
2    04-30-22
3    04-30-22
4    04-30-22
Name: Date, dtype: object

In [13]:
df['Unnamed: 22'].unique()

array([nan, False], dtype=object)

In [4]:
df.drop(columns=['Unnamed: 22'], inplace=True)

In [4]:
df.drop(columns=['index'], inplace=True)

In [5]:
df['Date'] = pd.to_datetime(
    df['Date'],
    format='%m-%d-%y',
    errors='coerce'
)

In [6]:
df['Date'].dtype

dtype('<M8[ns]')

In [7]:
df.duplicated().sum()

np.int64(6)

In [8]:
df[df.duplicated()]

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
30661,406-0372545-6086735,2022-04-12,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,L,...,NaN,NaN,Siliguri,WEST BENGAL,734008.0,IN,NaN,False,NaN,NaN
41292,408-0373839-4433120,2022-04-05,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,M,...,NaN,NaN,BENGALURU,KARNATAKA,560072.0,IN,NaN,False,NaN,NaN
79845,171-9628368-5329958,2022-05-07,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,L,...,NaN,NaN,ERNAKULAM,KERALA,682017.0,IN,NaN,False,NaN,False
85791,171-3249942-2207542,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,XL,...,INR,939.0,PUNE,MAHARASHTRA,411057.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
86419,405-8669298-3850736,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,3XL,...,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
98955,407-4853873-4978725,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,M,...,INR,1163.0,Zirakpur,Punjab,140603.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum()

Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7792
Amount                 7792
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49150
B2B                       0
fulfilled-by          89692
Unnamed: 22           49048
dtype: int64

In [5]:
(df.isnull().sum() / len(df) * 100).round(2)

index                  0.00
Order ID               0.00
Date                   0.00
Status                 0.00
Fulfilment             0.00
Sales Channel          0.00
ship-service-level     0.00
Style                  0.00
SKU                    0.00
Category               0.00
Size                   0.00
ASIN                   0.00
Courier Status         5.33
Qty                    0.00
currency               6.04
Amount                 6.04
ship-city              0.03
ship-state             0.03
ship-postal-code       0.03
ship-country           0.03
promotion-ids         38.11
B2B                    0.00
fulfilled-by          69.55
dtype: float64

In [6]:
df[df['Amount'].isna()]['Status'].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [7]:
df[df['Amount'].isna()]['currency'].value_counts(dropna=False)

currency
NaN    7795
Name: count, dtype: int64

In [8]:
df['Status'].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [11]:
df['Amount_Missing'] = df['Amount'].isna()

In [10]:
df[
    (df['Amount'].isna()) &
    (df['Status'].str.startswith('Shipped'))
][['Order ID', 'Status', 'Qty', 'Category', 'SKU', 'currency', 'Amount']].head(20)

,Order ID,Status,Qty,Category,SKU,currency,Amount
937,S02-5278980-4327051,Shipped,15,Blouse,BL017-63BLACK,NaN,NaN
1057,S02-9107114-0460608,Shipped,2,Set,SET315-KR-PP-XL,NaN,NaN
1615,405-7790745-1369118,Shipped,0,kurta,JNE3518-KR-M,NaN,NaN
1989,171-9673855-2321133,Shipped,0,Set,SET232-KR-PP-S,NaN,NaN
2424,404-7478762-7926753,Shipped,0,Set,SET331-KR-NP-S,NaN,NaN
2819,404-0814480-8157169,Shipped,0,kurta,JNE3291-KR-XL,NaN,NaN
3631,S02-1006261-5356758,Shipped,9,kurta,JNE2305-KR-533-L,NaN,NaN
3632,S02-3681731-6111841,Shipped,1,kurta,JNE2058-KR-339-L,NaN,NaN
3634,S02-1926028-4838217,Shipped,1,kurta,JNE3311-KR-A-XS,NaN,NaN
3636,S02-6828927-1180856,Shipped,13,kurta,JNE2305-KR-533-XXL,NaN,NaN
3637,S02-3409426-0744131,Shipped,2,Blouse,BL020-71RED,NaN,NaN
3886,S02-8357726-8633940,Shipped,1,Set,SET251-KR-PP-S,NaN,NaN
3887,S02-6358630-3384547,Shipped,1,Blouse,BL021-71BLACK,NaN,NaN
3888,S02-8920429-3367507,Shipped,1,Set,SET304-KR-DPT-XL,NaN,NaN
3889,S02-0827522-8659612,Shipped,1,Set,J0002-SKD-S,NaN,NaN
3890,S02-7924344-3280541,Shipped,1,kurta,JNE3567-KR-S,NaN,NaN
3891,S02-7832149-5714447,Shipped,1,kurta,JNE3405-KR-L,NaN,NaN
3892,S02-9649067-3246849,Shipped,1,kurta,JNE3291-KR-L,NaN,NaN
3893,S02-2310917-8166336,Shipped,1,kurta,JNE3405-KR-XL,NaN,NaN
3894,S02-0668744-7285638,Shipped,1,Set,J0012-SKD-XXL,NaN,NaN

In [12]:
sales_df = df[df['Amount'].notna()].copy()

In [13]:
sales_df.shape

(121180, 24)

In [14]:
sales_df['Amount'].isna().sum()

np.int64(0)

In [5]:
df[df['Courier Status'].isna()]['Status'].value_counts()

Status
Cancelled                       6861
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [6]:
df['Courier Status'] = df['Courier Status'].fillna('Not Applicable')

In [7]:
df['Courier Status'].isna().sum()

np.int64(0)

In [8]:
df['promotion-ids'].value_counts(dropna=False).head(10)

promotion-ids
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       49153
IN Core Free Shipping 2015/04/08 23-48-5-108                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              46100
Duplicated A12RHGVGRWOT3S 1560498941486                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     489
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-XX7G3ZRJJJ5LG,Amazon PLCC Free-Financing Universal Merchant AAT-LEHCKNDBJG64E,Amazon PLCC Free-Financing Universal Merchant AAT-DJVHCEV7D7RQY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      458
Duplicated AYTJSBA8ZOP16 1567159860988                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      433
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      316
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      305
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4      230
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-FYWJCQHU2XQ2U,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-URPEBMPS7TSPE,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-YZ2VQO2YM6YYM,Amazon PLCC Free-Financing Universal Merchant AAT-4EOBCMLXMLDGY,Amazon PLCC Free-Financing Universal Merchant AAT-UB6CYNTOQMM7C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                      206
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-YFJA6XMAMWZSK,Amazon PLCC Free-Financing Universal Merchant AAT-K66BSCE2J2V5E,Amazon PLCC Free-Financing Universal Merchant AAT-275LMAQ3T5REI,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                      201
Name: count, dtype: int64

In [9]:
df['promotion-ids'].value_counts(dropna=False).head(10)

promotion-ids
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       49153
IN Core Free Shipping 2015/04/08 23-48-5-108                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              46100
Duplicated A12RHGVGRWOT3S 1560498941486                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     489
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-XX7G3ZRJJJ5LG,Amazon PLCC Free-Financing Universal Merchant AAT-LEHCKNDBJG64E,Amazon PLCC Free-Financing Universal Merchant AAT-DJVHCEV7D7RQY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      458
Duplicated AYTJSBA8ZOP16 1567159860988                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      433
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      316
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      305
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4      230
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-FYWJCQHU2XQ2U,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-URPEBMPS7TSPE,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-YZ2VQO2YM6YYM,Amazon PLCC Free-Financing Universal Merchant AAT-4EOBCMLXMLDGY,Amazon PLCC Free-Financing Universal Merchant AAT-UB6CYNTOQMM7C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                      206
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-YFJA6XMAMWZSK,Amazon PLCC Free-Financing Universal Merchant AAT-K66BSCE2J2V5E,Amazon PLCC Free-Financing Universal Merchant AAT-275LMAQ3T5REI,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                      201
Name: count, dtype: int64

In [10]:
df['promotion-ids'] = df['promotion-ids'].fillna('No Promotion')

In [11]:
df['promotion-ids'].isna().sum()

np.int64(0)

In [3]:
df['fulfilled-by'].value_counts(dropna=False)

fulfilled-by
NaN          89698
Easy Ship    39277
Name: count, dtype: int64

In [5]:
df['fulfilled-by'] = df['fulfilled-by'].fillna('Not Applicable')

In [6]:
df['fulfilled-by'].isna().sum()

np.int64(0)

In [7]:
df[df['ship-city'].isna()][
    ['Order ID', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country']
]

,Order ID,ship-city,ship-state,ship-postal-code,ship-country
1871,404-0566904-4825137,NaN,NaN,NaN,NaN
1872,404-0566904-4825137,NaN,NaN,NaN,NaN
8752,406-4003386-8768363,NaN,NaN,NaN,NaN
11215,402-0107720-7057168,NaN,NaN,NaN,NaN
13252,407-4532637-8415521,NaN,NaN,NaN,NaN
15688,404-9229894-8608305,NaN,NaN,NaN,NaN
16787,402-4919636-4333150,NaN,NaN,NaN,NaN
18351,405-4927647-8064368,NaN,NaN,NaN,NaN
22930,402-8628677-0457954,NaN,NaN,NaN,NaN
24986,406-4079063-8291520,NaN,NaN,NaN,NaN
30379,404-7506843-7913132,NaN,NaN,NaN,NaN
37963,407-3064376-9158743,NaN,NaN,NaN,NaN
37964,407-3064376-9158743,NaN,NaN,NaN,NaN
60986,171-3257610-9237139,NaN,NaN,NaN,NaN
63040,402-1049475-3611523,NaN,NaN,NaN,NaN
73675,405-1356730-8598722,NaN,NaN,NaN,NaN
73746,407-4664354-2179554,NaN,NaN,NaN,NaN
73771,406-7680604-5439529,NaN,NaN,NaN,NaN
73772,406-7680604-5439529,NaN,NaN,NaN,NaN
73911,405-3420451-5230744,NaN,NaN,NaN,NaN
80011,171-4552355-0255565,NaN,NaN,NaN,NaN
80092,403-2857451-7335536,NaN,NaN,NaN,NaN
80455,171-4691098-8489159,NaN,NaN,NaN,NaN
84008,405-8605864-8021901,NaN,NaN,NaN,NaN
84757,402-8651786-0683548,NaN,NaN,NaN,NaN
104201,403-3190636-2013146,NaN,NaN,NaN,NaN
106498,402-8673941-7883531,NaN,NaN,NaN,NaN
124215,405-0340492-2359532,NaN,NaN,NaN,NaN
124357,405-5884153-9925116,NaN,NaN,NaN,NaN
124358,405-5884153-9925116,NaN,NaN,NaN,NaN
124359,405-5884153-9925116,NaN,NaN,NaN,NaN
125385,403-5172380-9787567,NaN,NaN,NaN,NaN
126620,403-4249038-6582716,NaN,NaN,NaN,NaN

In [8]:
df['ship-city'] = df['ship-city'].fillna('Unknown')
df['ship-state'] = df['ship-state'].fillna('Unknown')
df['ship-country'] = df['ship-country'].fillna('Unknown')

In [9]:
df['ship-postal-code'] = df['ship-postal-code'].fillna(-1)

In [10]:
df[['ship-city', 'ship-state', 'ship-postal-code', 'ship-country']].isnull().sum()

ship-city           0
ship-state          0
ship-postal-code    0
ship-country        0
dtype: int64

In [11]:
df['Qty'].value_counts().sort_index()

Qty
0      12807
1     115780
2        341
3         32
4          9
5          2
8          1
9          1
13         1
15         1
Name: count, dtype: int64

In [12]:
df['Qty'].describe()

count    128975.000000
mean          0.904431
std           0.313354
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          15.000000
Name: Qty, dtype: float64

In [13]:
df[df['Qty'] == 0]['Status'].value_counts()

Status
Cancelled                       12701
Shipped                            93
Shipped - Delivered to Buyer        8
Shipped - Returned to Seller        3
Pending                             2
Name: count, dtype: int64

In [14]:
df[
    (df['Qty'] == 0) &
    (df['Status'] != 'Cancelled')
][['Order ID', 'Status', 'Category', 'SKU', 'Amount', 'currency']].head(20)

,Order ID,Status,Category,SKU,Amount,currency
1615,405-7790745-1369118,Shipped,kurta,JNE3518-KR-M,NaN,NaN
1989,171-9673855-2321133,Shipped,Set,SET232-KR-PP-S,NaN,NaN
2424,404-7478762-7926753,Shipped,Set,SET331-KR-NP-S,NaN,NaN
2819,404-0814480-8157169,Shipped,kurta,JNE3291-KR-XL,NaN,NaN
9255,405-1892033-5435562,Shipped,Set,SET393-KR-NP-S,NaN,NaN
11145,404-7498280-7477149,Shipped,Set,SET197-KR-NP-XXL,NaN,NaN
15881,406-5281014-6299540,Shipped,Top,JNE3690-TU-S,NaN,NaN
16191,408-3851867-4615501,Shipped,kurta,JNE3468-KR-L,NaN,NaN
16599,403-8676035-5065939,Shipped,Set,SET184-KR-PP-M,NaN,NaN
18336,405-1252351-8764324,Shipped,Set,NW036-ST-SR-M,NaN,NaN
18891,408-4196439-4813936,Shipped,kurta,J0053-KR-XS,NaN,NaN
18894,408-2656493-8935504,Shipped - Delivered to Buyer,Set,SET278-KR-NP-S,NaN,NaN
19292,408-0017934-6791513,Shipped - Delivered to Buyer,Set,SET288-KR-NP-XXL,NaN,NaN
20402,406-4339807-3944301,Shipped,kurta,JNE3465-KR-XL,NaN,NaN
20649,402-5900873-2675540,Shipped,Set,SET258-KR-PP-L,NaN,NaN
23873,407-5638769-8389162,Shipped - Delivered to Buyer,kurta,JNE3730-KR-L,NaN,NaN
24270,408-7280154-1992362,Shipped,kurta,JNE3534-KR-XS,NaN,NaN
24592,406-9799250-9247502,Shipped,Set,SET209-KR-PP-XXL,NaN,NaN
24643,402-3841973-7282702,Shipped,Set,J0095-SET-XXXL,NaN,NaN
26028,407-0717613-4338735,Shipped,Set,J0004-SKD-L,NaN,NaN

In [15]:
df[df['Amount'] < 0][['Order ID', 'Status', 'Qty', 'Category', 'Amount']].head(20)

Empty DataFrame
Columns: [Order ID, Status, Qty, Category, Amount]
Index: []

In [16]:
df['Amount'].describe()

count    121180.000000
mean        648.561465
std         281.211687
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64

In [17]:
df[df['Amount'] == 0]['Status'].value_counts()

Status
Shipped                          1518
Shipped - Delivered to Buyer      716
Shipped - Returned to Seller       51
Shipped - Picked Up                28
Pending                            17
Pending - Waiting for Pick Up       9
Shipped - Lost in Transit           2
Shipped - Returning to Seller       2
Name: count, dtype: int64

In [18]:
df['currency'].value_counts(dropna=False)

currency
INR    121180
NaN      7795
Name: count, dtype: int64

In [3]:
df['currency'] = df['currency'].fillna('Not Available')

In [4]:
df['currency'].isna().sum()

np.int64(0)

In [5]:
sales_df = df[df['Amount'].notna()].copy()

In [6]:
df['Date'].min()

'03-31-22'

In [7]:
df['Date'].max()

'06-29-22'

In [14]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month_name()
df['Month_Number'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [15]:
df[['Date', 'Year', 'Month', 'Month_Number', 'Day']].head()

        Date  Year  Month  Month_Number  Day
0 2022-04-30  2022  April             4   30
1 2022-04-30  2022  April             4   30
2 2022-04-30  2022  April             4   30
3 2022-04-30  2022  April             4   30
4 2022-04-30  2022  April             4   30

In [12]:
df['Date'] = pd.to_datetime(df['Date'], format='%m-%d-%y')

In [13]:
df['Date'].dtype

dtype('<M8[ns]')

In [16]:
sales_df = df[df['Amount'].notna()].copy()

In [17]:
sales_df.shape

(121180, 28)

In [18]:
sales_df['Amount'].isna().sum()

np.int64(0)

In [19]:
df['Sales'] = df['Amount']

In [20]:
df['Sales'].sum()

np.float64(78592678.3)

In [21]:
sales_df['Amount'].sum()

np.float64(78592678.30000001)

In [22]:
df['Order ID'].nunique()

120378

In [23]:
df['Order ID'].count()

np.int64(128975)

In [24]:
df['Order ID'].count()

np.int64(128975)

In [3]:
df['Qty'].sum()

np.int64(116649)

In [5]:
df['Sales'] = df['Amount']

In [6]:
df.groupby('Order ID')['Sales'].sum().mean()

np.float64(652.8824062536344)

In [7]:
df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

Category
Set              39204124.03
kurta            21299546.70
Western Dress    11216072.69
Top               5347792.30
Ethnic Dress       791217.66
Blouse             458408.18
Bottom             150667.98
Saree              123933.76
Dupatta               915.00
Name: Sales, dtype: float64

In [15]:
df.groupby(['Year', 'Month_Number', 'Month'])['Sales'].sum().sort_values()

Year  Month_Number  Month
2022  3             March      101683.85
      6             June     23425809.38
      5             May      26226476.75
      4             April    28838708.32
Name: Sales, dtype: float64

In [9]:
df['Date'] = pd.to_datetime(df['Date'], format='%m-%d-%y')

In [10]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month_name()
df['Month_Number'] = df['Date'].dt.month

In [11]:
df['Sales'] = df['Amount']

In [13]:
df.groupby(['Year', 'Month_Number', 'Month'])['Sales'].sum().sort_values()

Year  Month_Number  Month
2022  3             March      101683.85
      6             June     23425809.38
      5             May      26226476.75
      4             April    28838708.32
Name: Sales, dtype: float64

In [16]:
df.groupby('Status')['Sales'].sum().sort_values(ascending=False)

Status
Shipped                          50324255.0
Shipped - Delivered to Buyer     18650815.0
Cancelled                         6919284.3
Shipped - Returned to Seller      1269644.0
Shipped - Picked Up                661252.0
Pending                            430271.0
Pending - Waiting for Pick Up      192138.0
Shipped - Returning to Seller      107620.0
Shipped - Out for Delivery          26971.0
Shipped - Rejected by Buyer          7295.0
Shipped - Lost in Transit            1997.0
Shipped - Damaged                    1136.0
Shipping                                0.0
Name: Sales, dtype: float64

In [17]:
df.groupby('SKU')['Sales'].sum().sort_values(ascending=False).head(10)

SKU
J0230-SKD-M        527699.20
JNE3797-KR-L       524581.77
J0230-SKD-S        479937.14
JNE3797-KR-M       454290.16
JNE3797-KR-S       407302.57
JNE3797-KR-XL      332155.24
J0230-SKD-L        305616.95
JNE3797-KR-XS      303616.70
SET268-KR-NP-XL    284058.96
JNE3797-KR-XXXL    276375.80
Name: Sales, dtype: float64

In [18]:
df.groupby('ship-state')['Sales'].sum().sort_values(ascending=False).head(10)

ship-state
MAHARASHTRA       13335534.14
KARNATAKA         10481114.37
TELANGANA          6916615.65
UTTAR PRADESH      6816642.08
TAMIL NADU         6515650.11
DELHI              4235215.97
KERALA             3830227.58
WEST BENGAL        3507880.44
ANDHRA PRADESH     3219831.72
HARYANA            2882092.99
Name: Sales, dtype: float64

In [19]:
df.groupby('Fulfilment')['Sales'].sum().sort_values(ascending=False)

Fulfilment
Amazon      54322151.0
Merchant    24270527.3
Name: Sales, dtype: float64

In [20]:
df.groupby('B2B')['Sales'].sum().sort_values(ascending=False)

B2B
False    78001457.51
True       591220.79
Name: Sales, dtype: float64

In [3]:
df.to_csv("Amazon_Sales_Cleaned.csv", index=False)

In [5]:
import os
os.path.exists("Amazon_Sales_Cleaned.csv")

True

In [3]:
df.to_csv(r"C:\Users\HP\Downloads\Amazon_Sales_Cleaned.csv", index=False)